7/3/2019

This notebook is for the baseline experiments for predicting the condition the speaker is in. 

The baseline model will take an utterance as an input and perform a three-way prediction task. The choices for the prediction are "close"--all colors are similar, "split"--the target is similar to one distractor and disimilar to another, and "far", the target is disimilar from both distractors which in turn are disimilar to each other.

In [1]:
# so we can access classes from parent directory
import sys
sys.path.append("..")

In [21]:
from monroe_data import MonroeData, MonroeDataEntry, Color # for loading in training data
import caption_featurizers                              # for getting caption representations
import color_featurizers                                # for getting color representations
from experiment import FeatureHandler                   # for combining caption and color features

from models import PytorchModel, ConditionPredictor # model base that handles training / evaluation

In [119]:
import torch
import torch.nn as nn
import numpy as np
from sklearn.metrics import classification_report, accuracy_score

In [124]:
import importlib
import models
importlib.reload(models)
from models import PytorchModel, ConditionPredictor # model base that handles training / evaluation

In [3]:
# get data
train_data = MonroeData("../data/csv/train_corpus_monroe.csv", "../data/entries/train_entries_monroe.pkl")
dev_data = MonroeData("../data/csv/dev_corpus_monroe.csv", "../data/entries/dev_entries_monroe.pkl")

In [5]:
# define feature functions
caption_phi_character = caption_featurizers.CaptionFeaturizer(tokenizer = caption_featurizers.CharacterTokenizer)

# we use a color featurizer because the code was designed to always use both color and text features. These 
# features will just be ignored in the model code
color_phi = color_featurizers.ColorFeaturizer(color_featurizers.color_phi_fourier, "hsv", normalized=True)

In [13]:
# we define a mapping from condition to index from closest to farthest
condition_to_idx = {"close": 0, "split": 1, "far":2}

# condition predictor's target is to predict what color condition the participants were put in
def condition_predictor_target(data_entry):
    return condition_to_idx[data_entry.condition]

# pass in train and dev data, our caption and color feature functions, function for turning an element of our data
# (train or dev) into the target, we don't care about the colors at all, but the feature handler expects them.
# We set randomized_colors to false because our target function shouldn't need to take a color index
feature_handler = FeatureHandler(train_data, dev_data, caption_phi_character, color_phi, target_fn=condition_predictor_target, randomized_colors=False)

In [14]:
X_train = feature_handler.train_features()
y_train = feature_handler.train_targets()

In [112]:
# Now let's define the model:
class BaselineConditionPredictor(nn.Module):
    
    def __init__(self, vocab_size, embed_dim, speaker_hidden_dim, num_conditions=3):
        super(BaselineConditionPredictor, self).__init__()
        
        self.embed = nn.Embedding(vocab_size, embed_dim)
        
        self.speaker_lstm = nn.LSTM(embed_dim, speaker_hidden_dim, batch_first=True)
        self.linear = nn.Linear(speaker_hidden_dim, num_conditions)
        self.logsoftmax = nn.LogSoftmax(dim=1)
        
        
    def forward(self, color, caption):
        # disregard color because we don't care about it
        
        inputs = self.embed(caption)
        hidden, _ = self.speaker_lstm(inputs)
        last_hidden = hidden[:, -1, :]
        output_lin = self.linear(last_hidden)
        outputs = self.logsoftmax(output_lin)
        return outputs # let's just use the last embedding for the predictions

In [77]:
condition_predictor_character = ConditionPredictor(BaselineConditionPredictor, optimizer=torch.optim.Adam, lr=0.004, num_epochs=5)
condition_predictor_character.init_model(vocab_size=caption_phi_character.caption_indexer.size, 
                                         embed_dim=100, speaker_hidden_dim=100)

In [78]:
condition_predictor_character.fit(X_train, y_train)

---EPOCH 0---
0m 0s (0:0 0.00%) 0.0012
0m 6s (0:1000 7.90%) 1.0522
0m 13s (0:2000 15.79%) 1.0662
0m 20s (0:3000 23.69%) 1.0597
0m 29s (0:4000 31.58%) 1.0321
0m 37s (0:5000 39.48%) 1.0621
0m 44s (0:6000 47.37%) 1.0399
0m 51s (0:7000 55.27%) 1.0307
0m 58s (0:8000 63.17%) 1.0688
1m 4s (0:9000 71.06%) 1.0150
1m 11s (0:10000 78.96%) 1.0470
1m 17s (0:11000 86.85%) 1.0667
1m 23s (0:12000 94.75%) 1.0538
AFTER EPOCH 2999 - AVERAGE VALIDATION LOSS: 1.0571353808045387
---EPOCH 1---
1m 31s (1:0 0.00%) 0.0012
1m 37s (1:1000 7.90%) 1.0336
1m 45s (1:2000 15.79%) 1.0613
1m 52s (1:3000 23.69%) 1.0620
2m 0s (1:4000 31.58%) 1.0409
2m 7s (1:5000 39.48%) 1.0716
2m 15s (1:6000 47.37%) 1.0226
2m 22s (1:7000 55.27%) 1.0158
2m 29s (1:8000 63.17%) 1.0848
2m 36s (1:9000 71.06%) 1.0537
2m 42s (1:10000 78.96%) 1.0333
2m 48s (1:11000 86.85%) 1.0339
2m 54s (1:12000 94.75%) 1.0540
AFTER EPOCH 2999 - AVERAGE VALIDATION LOSS: 1.0473164211710293
---EPOCH 2---
3m 3s (2:0 0.00%) 0.0008
3m 10s (2:1000 7.90%) 1.0477
3m 17s 

In [79]:
condition_predictor_character.save_model("../model/condition_predictor_character.params")

In [40]:
X_assess = feature_handler.test_features()
y_assess = feature_handler.test_targets()

In [47]:
condition_predictor_character.load_model("../model/condition_predictor_character.params")

In [80]:
predictions_character = condition_predictor_character.predict(X_assess)

[-1.7478129 -1.3159838 -0.5840502]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2228812 -1.0489761 -1.034728 ]
[-1.3406556 -0.9936053 -0.9994374]
[-2.189497   -1.9687753  -0.28981888]
[-1.2167933  -0.96872765 -1.1262224 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2186503 -0.9709107 -1.121984 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.0800321 -1.2433364 -0.9888747]
[-1.2538704 -0.9882405 -1.0718606]
[-1.2711487 -1.0233942 -1.0213245]
[-2.189497   -1.9687753  -0.28981888]
[-1.0752101  -1.2395554  -0.99625164]
[-1.216706  -0.9686061 -1.1264443]
[-2.3795917  -1.5385686  -0.36712444]
[-2.662344   -1.7603421  -0.27676904]
[-1.2493832  -0.99510294 -1.068181  ]
[-2.5155637 -1.8459495 -0.2727182]
[-1.345469   -0.99478644 -0.99484676]
[-1.1131723  -1.2484732  -0.95570177]
[-2.3795917  -1.5385686  -0.36712444]
[-2.1442528  -1.7235308  -0.35039547]
[-1.0762403 -1.2403421 -0.9946845]
[-1.0123879 -1.1114081 -1.1791033]
[-1.3404921  -0.99405944 -0.9990971 ]
[-1.4208044 -0.9853

[-0.81994075 -1.0382165  -1.5825206 ]
[-1.4858708  -1.086327   -0.82956016]
[-1.6369196  -1.3771482  -0.59217227]
[-1.2622347 -1.080103  -0.9744004]
[-1.0915445 -1.0124642 -1.2007121]
[-0.81986266 -1.0379503  -1.5831466 ]
[-1.2228725  -0.97632277 -1.1119318 ]
[-1.218107   -0.96889466 -1.1248283 ]
[-1.4508487  -0.99412    -0.92740285]
[-1.4664223  -0.93486583 -0.97653997]
[-1.4660901  -0.93187416 -0.97987294]
[-2.3795917  -1.5385686  -0.36712444]
[-1.038727  -1.0340203 -1.2360808]
[-1.2953483 -1.0092018 -1.016974 ]
[-2.1442528  -1.7235308  -0.35039547]
[-0.8198785 -1.0378687 -1.5832534]
[-0.83225477 -1.0390424  -1.5552363 ]
[-2.662344   -1.7603421  -0.27676904]
[-1.8630877 -1.2943213 -0.5608505]
[-2.189497   -1.9687753  -0.28981888]
[-0.82580894 -1.0395093  -1.5678582 ]
[-1.2490747 -0.9974675 -1.0659001]
[-1.1255828 -1.1028838 -1.0682068]
[-2.1442528  -1.7235308  -0.35039547]
[-2.3795917  -1.5385686  -0.36712444]
[-1.8630877 -1.2943213 -0.5608505]
[-2.1442528  -1.7235308  -0.35039547]
[

[-1.4285569  -1.0290843  -0.90879047]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.017827  -0.9708915 -1.347553 ]
[-0.84398365 -1.0682447  -1.4854753 ]
[-1.6369196  -1.3771482  -0.59217227]
[-1.2712724 -1.020258  -1.0243673]
[-1.3616719  -1.1150126  -0.87741417]
[-1.4285569  -1.0290843  -0.90879047]
[-1.0755647 -1.0751712 -1.1467875]
[-2.3795917  -1.5385686  -0.36712444]
[-1.0453545 -0.9722612 -1.3085709]
[-1.3794013 -1.2076778 -0.799886 ]
[-1.463311   -0.9306163  -0.98290914]
[-1.0453902 -0.9722612 -1.3085239]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2168963 -0.9686432 -1.126227 ]
[-1.2709011 -1.0061768 -1.0390033]
[-0.99085987 -1.0571878  -1.2682935 ]
[-2.1442528  -1.7235308  -0.35039547]
[-1.9264256 -1.6213034 -0.4205415]
[-2.5155637 -1.8459495 -0.2727182]
[-1.7934551 -1.140372  -0.6656961]
[-1.27745   -1.4066553 -0.7417252]
[-2.4426932 -1.958077  -0.2588433]
[-1.6369196  -1.3771482  -0.59217227]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.3877192 -1.2269788 -0.7826802]
[-0.8295465 -1.0397956 -1

[-1.288087  -1.0258365 -1.0059266]
[-1.249067   -0.99744654 -1.0659289 ]
[-2.189497   -1.9687753  -0.28981888]
[-1.8630877 -1.2943213 -0.5608505]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2736535 -1.1387703 -0.9163409]
[-1.0609115 -1.0536181 -1.1868341]
[-1.3094013 -1.0140648 -1.0016395]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.4852024 -1.3265032 -0.6769986]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.4852024 -1.3265032 -0.6769986]
[-1.3867068 -1.1649377 -0.8251688]
[-1.9264256 -1.6213034 -0.4205415]
[-2.662344   -1.7603421  -0.27676904]
[-1.4852024 -1.3265032 -0.6769986]
[-2.3795917  -1.5385686  -0.36712444]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.01531    -1.6818885  -0.38463572]
[-1.1837186 -1.1153889 -1.0049195]
[-1.0506017 -0.9752315 -1.2976693]
[-1.3426945 -1.192847  -0.8312548]
[-1.6027699  -1.200062   -0.69818705]
[-2.1801333 -1.7877433 -0.3290094]
[-1.8193091 -1.2939634 -0.5732679]
[-1.4514549 -1.1153283 -0.8256207]
[-2.3795917  -1.5385686  -0.36712444]

[-1.340225  -0.9936483 -0.9997003]
[-1.2882123 -1.1707139 -0.881669 ]
[-1.3401432  -0.9935681  -0.99983925]
[-1.3457704 -1.0175192 -0.9724106]
[-1.3777623 -1.0062432 -0.9616334]
[-1.2674143 -1.0081223 -1.0397646]
[-1.2488447  -0.99455774 -1.0692173 ]
[-0.82998127 -1.0669703  -1.5146129 ]
[-1.0391161 -1.0345155 -1.2350018]
[-1.2882123 -1.1707139 -0.881669 ]
[-1.0391161 -1.0345155 -1.2350018]
[-1.2523069  -0.98727065 -1.0742228 ]
[-1.2808242 -1.1689974 -0.8879136]
[-1.2085779 -0.8879516 -1.2382865]
[-1.0153837 -0.9309887 -1.4123392]
[-0.91981024 -0.93436044 -1.5674889 ]
[-1.0754204 -1.0746931 -1.1474564]
[-1.1081288 -1.044807  -1.1455024]
[-2.017219  -1.6879745 -0.3826062]
[-1.4322246 -1.0288286 -0.9068419]
[-2.017219  -1.6879745 -0.3826062]
[-1.7478129 -1.3159838 -0.5840502]
[-1.8630877 -1.2943213 -0.5608505]
[-2.662344   -1.7603421  -0.27676904]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.4322246 -1.0288286 -0.9068419]
[-1.5319409 -1.0601026 -0.826761 ]
[-1.2624154 -0.9994466 -1.0528347]
[-

[-1.0831584 -1.0837042 -1.1296837]
[-2.5155637 -1.8459495 -0.2727182]
[-2.189497   -1.9687753  -0.28981888]
[-1.0349013 -1.2342746 -1.0393268]
[-0.87894434 -1.0767813  -1.4102242 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2256694 -0.975567  -1.1102992]
[-1.2257063  -0.97589284 -1.1098936 ]
[-0.9262869 -1.0527773 -1.3664474]
[-1.0193157 -1.093675  -1.1901516]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2171451 -0.9691241 -1.1254373]
[-1.6369196  -1.3771482  -0.59217227]
[-1.3094013 -1.0140648 -1.0016395]
[-1.4278497  -1.0284823  -0.90974545]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.408026  -1.0879214 -0.8711784]
[-2.662344   -1.7603421  -0.27676904]
[-0.82580894 -1.0395093  -1.5678582 ]
[-1.3465776  -0.9956844  -0.99317026]
[-1.0789682 -1.0756252 -1.1426599]
[-0.82191545 -1.0375035  -1.5795248 ]
[-2.3795917  -1.5385686  -0.36712444]
[-2.662344   -1.7603421  -0.27676904]
[-1.1255828 -1.1028838 -1.0682068]
[-1.1553963  -0.98352575 -1.1677145 ]
[-1.4278497  -1.0284823  -0.90974545]
[-1.2167301  

[-1.9264256 -1.6213034 -0.4205415]
[-1.2492015 -0.9949464 -1.068501 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2269592  -0.97118336 -1.1141853 ]
[-1.3410015 -0.9938218 -0.9989738]
[-1.531194  -1.0622406 -0.8254397]
[-1.2492015 -0.9949464 -1.068501 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.8630877 -1.2943213 -0.5608505]
[-2.1442528  -1.7235308  -0.35039547]
[-1.2647241 -1.0208696 -1.0288961]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2508459 -0.9954567 -1.0665824]
[-1.2181356  -0.96892184 -1.1247709 ]
[-1.2687905 -1.0052599 -1.0416301]
[-1.2985736 -1.1579252 -0.8844483]
[-2.662344   -1.7603421  -0.27676904]
[-1.3399968 -0.9934936 -1.0000184]
[-1.6369196  -1.3771482  -0.59217227]
[-1.3351212  -1.1108402  -0.89748967]
[-1.7475926 -1.4801046 -0.5138413]
[-2.1442528  -1.7235308  -0.35039547]
[-2.662344   -1.7603421  -0.27676904]
[-1.2680762 -1.1514494 -0.910186 ]
[-0.80905056 -1.0637691  -1.5627118 ]
[-1.2167072  -0.96860164 -1.1264484 ]
[-1.2492015 -0.9949464 -1.068501 ]
[-1.0562663 -1.0683

[-1.4278497  -1.0284823  -0.90974545]
[-1.5485256 -1.0454397 -0.8303388]
[-2.662344   -1.7603421  -0.27676904]
[-1.2629768 -1.0015087 -1.0502099]
[-1.0661287 -1.2368803 -1.0068375]
[-0.94941634 -1.060786   -1.3210702 ]
[-1.0622373 -1.1495016 -1.086119 ]
[-1.0349013 -1.2342746 -1.0393268]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2726183 -1.0956422 -0.9530122]
[-0.8976547 -1.0261548 -1.4520354]
[-2.662344   -1.7603421  -0.27676904]
[-1.53212   -1.0602102 -0.8265873]
[-2.662344   -1.7603421  -0.27676904]
[-1.3567598 -1.012254  -0.9699362]
[-1.6369196  -1.3771482  -0.59217227]
[-1.2167065 -0.9686037 -1.1264465]
[-1.0387533 -1.0340788 -1.2359773]
[-1.3458719  -0.9951173  -0.99423254]
[-2.1442528  -1.7235308  -0.35039547]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2269366 -0.9707982 -1.1146502]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.3479583 -0.9961533

[-0.9198124 -0.9343615 -1.5674825]
[-1.0149179 -0.9310656 -1.4129081]
[-1.0682163  -0.94496167 -1.3179456 ]
[-1.0148962 -0.93141   -1.4123831]
[-0.9198126 -0.9343609 -1.5674832]
[-1.0147216  -0.93353957 -1.4092064 ]
[-1.0147221  -0.93354005 -1.4092054 ]
[-1.0149153  -0.93140185 -1.4123678 ]
[-1.0149187 -0.9310653 -1.4129074]
[-0.9198126 -0.9343609 -1.5674832]
[-1.119142   -0.93685794 -1.2673278 ]
[-1.0149187 -0.9310653 -1.4129074]
[-1.0259198  -0.93300045 -1.3936746 ]
[-1.0147238  -0.93353826 -1.4092057 ]
[-0.9198126 -0.9343609 -1.5674832]
[-1.1191559 -0.9368543 -1.2673168]
[-1.0679464  -0.94475055 -1.3185989 ]
[-0.9198124 -0.9343615 -1.5674825]
[-1.0149179 -0.9310643 -1.4129105]
[-1.0149186 -0.9310688 -1.412902 ]
[-0.91981256 -0.93436074 -1.5674835 ]
[-1.1191264 -0.9368602 -1.2673433]
[-1.2488455  -0.99456084 -1.0692136 ]
[-0.91981256 -0.93436074 -1.5674835 ]
[-1.0147226 -0.9335371 -1.4092094]
[-0.91981274 -0.9343613  -1.5674827 ]
[-1.0147228  -0.93353873 -1.4092062 ]
[-1.0147233  -0.

[-1.2167068  -0.96860147 -1.126449  ]
[-0.830446  -1.0668304 -1.5139107]
[-1.2488415  -0.99455935 -1.0692184 ]
[-0.8198742 -1.0378742 -1.5832531]
[-1.4287181 -1.2819045 -0.7279957]
[-1.2508459 -0.9954567 -1.0665824]
[-1.4647374  -0.9499208  -0.96210015]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2259076  -0.97572166 -1.1099102 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-0.93875885 -1.0318985  -1.3761176 ]
[-2.189497   -1.9687753  -0.28981888]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2302563 -0.9795669 -1.101691 ]
[-2.5155637 -1.8459495 -0.2727182]
[-1.2169706 -0.969108  -1.1256154]
[-1.2382679  -0.99426484 -1.0784605 ]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2882988  -1.0923297  -0.94462216]
[-1.2302563 -0.9795669 -1.101691 ]
[-1.2253627 -1.051943  -1.0297666]
[-1.644039   -1.2956377  -0.62908626]
[-2.189497   -1.9687753  -0.28981888]
[-1.2167338 -0.9686074 -1.126417 ]
[-1.3403261  -0.99376255 -0.99951345]
[-1.3515389 -1.0794418 -0.9128637]
[-1.2459798  -0.99964124 -1.0661557 ]
[-1.8630877 -

[-1.0149889  -0.93109435 -1.4127557 ]
[-1.6880525  -1.155371   -0.69278705]
[-1.3113366 -1.0210196 -0.993407 ]
[-1.4029635  -1.0405735  -0.91409135]
[-1.4103433 -1.4470266 -0.6526356]
[-1.0130213 -1.0599064 -1.2365252]
[-1.0766168 -0.9565319 -1.2908732]
[-0.8408204 -1.0544    -1.5130277]
[-2.5155637 -1.8459495 -0.2727182]
[-1.0595345 -1.0794977 -1.1595834]
[-1.1592767 -0.9431537 -1.2143962]
[-1.8630877 -1.2943213 -0.5608505]
[-0.8421707 -1.0748571 -1.4789401]
[-1.1192055  -0.93958443 -1.2634728 ]
[-0.9201361 -0.9342767 -1.5670238]
[-1.036771  -1.0778004 -1.1872507]
[-1.0260715  -0.93303347 -1.3934029 ]
[-1.9184439  -1.4241636  -0.49027973]
[-2.3795917  -1.5385686  -0.36712444]
[-2.189497   -1.9687753  -0.28981888]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.189497   -1.9687753  -0.28981888]
[-1.0895015 -1.2255108 -0.9942303]
[-1.9264256 -1.6213034 -0.4205415]
[-0.91982454 -0.93436176 -1.5674589 ]
[-1.3428216 -0.9950709 -0.9964306]
[-0.91983044 -0.9343629  -1.5674458 ]
[-1.8956025  -1.28195 

[-1.27745   -1.4066553 -0.7417252]
[-1.0082031 -1.2529073 -1.0513864]
[-2.5155637 -1.8459495 -0.2727182]
[-2.662344   -1.7603421  -0.27676904]
[-1.6369196  -1.3771482  -0.59217227]
[-2.3795917  -1.5385686  -0.36712444]
[-1.1567624 -1.0024036 -1.1441299]
[-1.3905909 -1.0376248 -0.9243818]
[-1.6369196  -1.3771482  -0.59217227]
[-1.1546466  -0.98335856 -1.1686754 ]
[-1.262977  -1.0015095 -1.0502092]
[-1.4285569  -1.0290843  -0.90879047]
[-2.3795917  -1.5385686  -0.36712444]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.6369196  -1.3771482  -0.59217227]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.0490074 -1.036039  -1.2212638]
[-1.21671   -0.9686061 -1.1264408]
[-1.2167075 -0.9686062 -1.1264429]
[-0.81931263 -1.0912595  -1.4984684 ]
[-1.242314  -1.0255064 -1.042223 ]
[-1.2617496 -1.0016084 -1.0510985]
[-1.2508459 -0.9954567 -1.0665824]
[-1.2181904  -0.96970516 -1.1238062 ]
[-1.2167133 -0.9686067 -1.1264368]
[-1.6692688 -1.2645419 -0.6363007]
[-1.5396142 -1.0914117 -0

[-0.8198145 -1.0380346 -1.5831048]
[-1.2489179  -0.99456215 -1.0691518 ]
[-1.3400234  -0.99350584 -0.99998724]
[-1.0525028 -1.0595517 -1.1896565]
[-0.84504807 -1.066644   -1.4858863 ]
[-1.2181113 -0.9689006 -1.1248176]
[-1.464123  -1.2781942 -0.7129839]
[-1.2167186 -0.9686072 -1.1264315]
[-1.2522225  -0.98699707 -1.0745919 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2561284 -1.0212218 -1.035381 ]
[-1.1807032 -0.9570808 -1.1746569]
[-2.662344   -1.7603421  -0.27676904]
[-1.2816893 -1.0065618 -1.0301354]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2167202  -0.96860385 -1.1264341 ]
[-1.2496147  -0.99790186 -1.064986  ]
[-1.0725513 -1.0733497 -1.1520003]
[-1.2478657  -0.99565005 -1.0688598 ]
[-1.276206  -1.0044655 -1.0365802]
[-1.2104349 -0.9895594 -1.1080812]
[-1.1017226 -1.0437713 -1.1533506]
[-1.2167065 -0.9686021 -1.1264484]
[-1.2508459 -0.9954567 -1.0665824]
[-1.530992  -1.0622864 -0.8255033]
[-1.0387255 -1.0340538 -1.2360418]
[-1.2167196  -0.96860427 -1.1264338 ]
[-1.2624282 -1.1400206 -0.92

[-1.2167082 -0.9685948 -1.1264555]
[-1.0425113  -0.91893864 -1.3923541 ]
[-1.2234674 -0.9737082 -1.1144006]
[-1.1498443  -1.2793239  -0.90364945]
[-1.0308416 -0.9050391 -1.4322659]
[-2.5155637 -1.8459495 -0.2727182]
[-1.0813559 -1.0803751 -1.1350801]
[-1.0323867 -0.9049225 -1.4301594]
[-1.029988  -0.9041321 -1.4350826]
[-0.98655313 -1.1369443  -1.1830513 ]
[-1.4959271 -0.9489231 -0.9446863]
[-1.4658921  -0.93195677 -0.979908  ]
[-1.2736685  -1.1478556  -0.90911615]
[-1.8630877 -1.2943213 -0.5608505]
[-1.388451   -1.222068   -0.78544164]
[-1.0749323 -1.2063793 -1.0233186]
[-1.0387199 -1.0340612 -1.2360399]
[-2.1442528  -1.7235308  -0.35039547]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2188674 -0.9703195 -1.1224747]
[-1.5452344  -0.93780047 -0.92823654]
[-1.3377097  -1.1409504  -0.87218124]
[-1.2816694 -1.0065595 -1.0301533]
[-1.2617877 -0.9990297 -1.0537841]
[-1.3786566 -0.9526315 -1.015121 ]
[-1.260227  -0.9978241 -1.0563302]
[-1.0382769 -0.9093361 -1.4141008]
[-1.6298681  -1.1463253  -0.

[-1.0671394 -0.9441195 -1.3205559]
[-2.13209   -1.6951191 -0.3597747]
[-1.2281294  -0.97177243 -1.1124626 ]
[-1.659905   -1.1701038  -0.69413114]
[-0.9533561 -1.0623045 -1.3134291]
[-1.2269585 -0.9708052 -1.1146221]
[-0.94185126 -0.9506084  -1.4979464 ]
[-1.2167497  -0.96862066 -1.1263872 ]
[-1.3175836 -1.0506725 -0.960985 ]
[-1.2167273 -0.9686144 -1.126415 ]
[-1.0754204 -1.0746931 -1.1474564]
[-0.9046836 -0.9358102 -1.5942432]
[-1.2167068 -0.9686016 -1.1264489]
[-1.3410015 -0.9938218 -0.9989738]
[-1.0582544 -1.060188  -1.18238  ]
[-2.189497   -1.9687753  -0.28981888]
[-2.1442528  -1.7235308  -0.35039547]
[-1.1313722 -0.9399507 -1.2491004]
[-1.2493832  -0.99510294 -1.068181  ]
[-1.2167084 -0.9686568 -1.1263828]
[-1.5029271 -1.1075578 -0.8048451]
[-0.9891487 -1.0875754 -1.2341769]
[-0.96157587 -1.0677366  -1.2949035 ]
[-1.1159697 -0.9365784 -1.2714106]
[-1.9557979 -1.2525153 -0.5572826]
[-1.2490454 -0.9947098 -1.0688863]
[-2.1442528  -1.7235308  -0.35039547]
[-1.8630877 -1.2943213 -0.56

[-1.33516    -1.0290303  -0.96882004]
[-1.7809217 -1.4314935 -0.523294 ]
[-2.189497   -1.9687753  -0.28981888]
[-2.1442528  -1.7235308  -0.35039547]
[-2.662344   -1.7603421  -0.27676904]
[-2.1442528  -1.7235308  -0.35039547]
[-2.3795917  -1.5385686  -0.36712444]
[-1.7809217 -1.4314935 -0.523294 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.0754143 -1.0746902 -1.1474663]
[-2.3795917  -1.5385686  -0.36712444]
[-1.7478129 -1.3159838 -0.5840502]
[-1.1022142 -1.0443275 -1.1522133]
[-1.7478129 -1.3159838 -0.5840502]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3795917  -1.5385686  -0.36712444]
[-2.189497   -1.9687753  -0.28981888]
[-1.7478129 -1.3159838 -0.5840502]
[-2.3795917  -1.5385686  -0.36712444]
[-1.9595022  -1.6580477  -0.40262792]
[-0.88992256 -1.0798655  -1.3876102 ]
[-1.6123599  -1.3264189  -0.62519425]
[-1.8716068 -1.3797073 -0.5200823]
[-2.5155637 -1.8459495 -0.2727182]
[-1.8630877 -1.2943213 -0.5608505]
[-1.7478129 -1.3159838 -0.5840502]
[-2.1442528  -1.7235308  -0.35039547]
[-1.3357418  

[-2.3795917  -1.5385686  -0.36712444]
[-1.8630877 -1.2943213 -0.5608505]
[-2.01531    -1.6818885  -0.38463572]
[-1.0387232 -1.0340557 -1.2360423]
[-1.5318878 -1.0600581 -0.8268226]
[-0.8321061 -1.0687071 -1.5077125]
[-1.3439734 -0.9980199 -0.992675 ]
[-1.3865213  -1.1647501  -0.82540816]
[-0.8321061 -1.0687071 -1.5077125]
[-1.0451324 -1.1004547 -1.1531688]
[-2.189497   -1.9687753  -0.28981888]
[-1.1530938 -1.17836   -0.9766826]
[-1.4159968 -1.1051841 -0.8529251]
[-1.7478129 -1.3159838 -0.5840502]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.7478129 -1.3159838 -0.5840502]
[-0.8321061 -1.0687071 -1.5077125]
[-1.7478129 -1.3159838 -0.5840502]
[-1.0730951 -1.0736431 -1.1510948]
[-1.7478129 -1.3159838 -0.5840502]
[-0.83045065 -1.0668292  -1.5139031 ]
[-1.2181401 -0.9689748 -1.1247046]
[-1.7478129 -1.3159838 -0.5840502]
[-1.7478129 -1.3159838 -0.5840502]
[-1.1962779  -1.2917092  -0.86066216]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.1442528  -1.7235308  -0.35039547]
[-0.92971814 -1.0520993  -1.362065

[-1.5478563 -1.0350611 -0.839117 ]
[-1.8630877 -1.2943213 -0.5608505]
[-1.6369196  -1.3771482  -0.59217227]
[-1.2167065 -0.9686034 -1.1264468]
[-1.2167066 -0.9685992 -1.1264517]
[-1.2555271 -1.0000881 -1.0577756]
[-1.2818124 -1.0143945 -1.0220839]
[-0.84349656 -1.0669847  -1.488318  ]
[-1.252277  -0.9868779 -1.0746763]
[-1.2720124 -1.0145788 -1.0295215]
[-1.0659404 -1.1411779 -1.090187 ]
[-1.3152094 -1.0499513 -0.9633114]
[-1.3244739 -1.0706995 -0.9383103]
[-1.0807843 -1.1553001 -1.0621614]
[-1.2353067 -1.1320078 -0.9496688]
[-1.3244739 -1.0706995 -0.9383103]
[-1.2631968  -0.99240613 -1.0596775 ]
[-1.5957892  -1.074723   -0.78557116]
[-1.2687905 -1.0052599 -1.0416301]
[-1.2025337  -1.3498154  -0.82034475]
[-0.8435678 -1.0669687 -1.4882073]
[-1.3553882  -1.0836391  -0.90685815]
[-1.2490644 -0.9974446 -1.0659332]
[-1.5993807 -1.2386212 -0.6768902]
[-1.5258057  -1.1008834  -0.79855883]
[-1.2181096 -0.9689474 -1.1247644]
[-1.5957892  -1.074723   -0.78557116]
[-1.2616415  -1.1043351  -0.953

[-1.0721912 -1.073186  -1.1525675]
[-0.8703399 -1.0352486 -1.486987 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.1837186 -1.1153889 -1.0049195]
[-1.192847  -1.207128  -0.9223371]
[-1.8081901 -1.1739321 -0.6407436]
[-1.0729076 -1.0735073 -1.1514444]
[-2.3795917  -1.5385686  -0.36712444]
[-1.3399966 -0.9934866 -1.0000255]
[-1.3786566 -0.9526315 -1.015121 ]
[-1.0835398 -1.0766557 -1.1367148]
[-1.3851122 -0.9574897 -1.0055346]
[-1.2488674 -0.9945797 -1.0691748]
[-0.92617905 -1.0526847  -1.3667415 ]
[-1.3399967 -0.9934871 -1.0000252]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2167059 -0.9686059 -1.1264445]
[-1.2488742 -0.9949562 -1.0687637]
[-1.8827178  -1.2568153  -0.57400465]
[-0.924032  -0.9374248 -1.5537695]
[-0.89899766 -0.93681085 -1.603719  ]
[-1.2488469  -0.99461496 -1.069154  ]
[-0.9755872 -0.9376207 -1.4633019]
[-1.2167059  -0.96860635 -1.1264441 ]
[-1.8630877 -1.2943213 -0.5608505]
[-1.6369196  -1.3771482  -0.59217227]
[-0.89979506 -1.0888112  -1.

[-2.3660455 -1.7839618 -0.303571 ]
[-1.7289205  -1.6906877  -0.44921106]
[-1.3400618  -0.9935415  -0.99992406]
[-1.3392675 -1.2107208 -0.8210257]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.7809217 -1.4314935 -0.523294 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2167072  -0.96860325 -1.1264464 ]
[-1.255101  -1.0026877 -1.0553778]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.3245947 -1.0345788 -0.9709758]
[-1.4424462 -1.0052667 -0.922047 ]
[-1.2828662  -1.1503682  -0.90081555]
[-1.7478129 -1.3159838 -0.5840502]
[-1.2167709 -0.9686353 -1.1263505]
[-1.7434664 -1.395056  -0.549449 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.075805  -1.0752829 -1.1464096]
[-1.4947548 -0.9471105 -0.947172 ]
[-1.4685806 -0.9517745 -0.9579139]
[-1.2181326  -0.96896696 -1.1247207 ]
[-1.2860916  -0.98503715 -1.0491772 ]
[-1.2492015 -0.9949464 -1.06850

[-1.265363  -1.0201759 -1.0290911]
[-1.2508459 -0.9954567 -1.0665824]
[-1.2617496 -1.0016084 -1.0510985]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2169676  -0.96872914 -1.1260612 ]
[-0.8200388 -1.0381219 -1.5824733]
[-1.072246  -1.0758144 -1.149671 ]
[-1.0778888 -1.226941  -1.0037602]
[-1.3410084  -0.99382734 -0.99896336]
[-1.1132488  -1.1978507  -0.99515086]
[-2.189497   -1.9687753  -0.28981888]
[-1.3279514  -1.4954884  -0.67169625]
[-1.2629304 -1.0003042 -1.0515138]
[-1.5309582  -1.0594031  -0.82780147]
[-1.4215872  -1.2229079  -0.76723206]
[-0.8202802 -1.0378963 -1.5823452]
[-1.3348678 -1.5173302 -0.6587256]
[-1.3401908  -0.99371755 -0.999655  ]
[-2.189497   -1.9687753  -0.28981888]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2167096 -0.9686032 -1.1264443]
[-1.8630877 -1.2943213 -0.5608505]
[-2.189497   -1.9687753  -0.28981888]
[-1.6369196  -1.3771482  -0.59217227]
[-1.288087  -1.0258365 -1.0059266]
[-1.4741075 -1.0155923 -0.894458 ]
[-1.0730951 -1.0736

[-0.9145874 -1.0932932 -1.3310223]
[-1.2167296  -0.96861666 -1.1264102 ]
[-0.9051066 -1.0879474 -1.3524964]
[-1.6398387  -1.363158   -0.59758765]
[-1.1715593 -1.2564392 -0.9027557]
[-1.0729071 -1.0735093 -1.1514425]
[-0.99565506 -1.1894593  -1.1204503 ]
[-0.90644574 -1.0881305  -1.3501676 ]
[-0.9066333 -1.0880888 -1.3499293]
[-1.2500398 -0.9955573 -1.0671452]
[-1.546305   -0.937959   -0.92750245]
[-1.216707  -0.968601  -1.1264492]
[-0.90498865 -1.087916   -1.3527219 ]
[-1.5789523  -1.0946369  -0.77838284]
[-0.95445615 -1.063057   -1.3108895 ]
[-0.90625906 -1.0880504  -1.3505623 ]
[-0.9079578 -1.0879092 -1.3481022]
[-1.0381829 -0.9112227 -1.4111195]
[-1.1093161 -1.1205571 -1.066772 ]
[-0.82093596 -1.0381197  -1.5805566 ]
[-1.589536  -1.2452061 -0.6770805]
[-1.1524683 -1.1406593 -1.0091312]
[-1.0582676 -1.0629221 -1.1792847]
[-0.9294884 -1.0520953 -1.3624251]
[-0.9262785 -1.0527724 -1.366467 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-0.9259683 -1.0861702 -1.3229601]
[-1.0524129 -1.059539  -1

[-1.2167144  -0.96860814 -1.1264342 ]
[-1.3421562 -0.994289  -0.9976854]
[-2.189497   -1.9687753  -0.28981888]
[-1.2628357 -1.0020896 -1.0497143]
[-1.3410015 -0.9938218 -0.9989738]
[-1.3804195  -0.95338684 -1.0130947 ]
[-1.2218549 -0.9731194 -1.1165279]
[-1.3402293 -0.9936499 -0.9996957]
[-1.3410084  -0.99382734 -0.99896336]
[-1.3422027  -0.99429774 -0.99764395]
[-1.3402779  -0.9937627  -0.99954754]
[-1.0729073 -1.0735074 -1.1514448]
[-1.8204318  -1.419034   -0.51735246]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.629535  -1.1073561 -0.7475024]
[-1.0355788 -1.0930483 -1.1718735]
[-1.8204318  -1.419034   -0.51735246]
[-1.079728  -1.071048  -1.1467645]
[-1.6369196  -1.3771482  -0.59217227]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.8204318  -1.419034   -0.51735246]
[-0.8328611 -1.0673363 -1.5083575]
[-1.0725394 -1.0733471 -1.1520163]
[-1.2196691 -0.9708634 -1.1211147]
[-1.4815267 -1.0600917 -0.8526459]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0754143 -1.0746902 -1.1474663]
[-1.2167071  -0.96860147 

[-1.0194257 -1.093686  -1.1900091]
[-1.0977991 -1.0759097 -1.1226752]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2167072 -0.9686004 -1.12645  ]
[-1.0404823 -0.9111606 -1.4078922]
[-1.2488534  -0.99456376 -1.0692039 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.1417972 -1.1041356 -1.0519446]
[-1.3422378  -0.99435365 -0.99756265]
[-1.0583897 -1.0601578 -1.1822613]
[-1.0896665 -1.0994743 -1.1067699]
[-1.2301762 -0.9584694 -1.1261494]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2649169 -1.0245129 -1.0250851]
[-1.2266212 -0.9711228 -1.1145573]
[-1.0387549 -1.0341141 -1.2359321]
[-0.92992735 -1.0487771  -1.3662887 ]
[-1.2508459 -0.9954567 -1.0665824]
[-2.662344   -1.7603421  -0.27676904]
[-1.2624665 -0.9992732 -1.052976 ]
[-1.7478129 -1.3159838 -0.5840502]
[-1.4437649 -1.0055492 -0.9210045]
[-1.4836923  -1.23411    -0.72958815]
[-1.2726183 -1.0956422 -0.9530122]
[-1.530338  -1.0587113 -0.8286578]
[-1.6369196  -1.3771482  -0.59217227]

[-1.2830433 -1.1559889 -0.8963376]
[-1.248874  -0.9949586 -1.0687616]
[-1.2705188  -1.1367406  -0.92017114]
[-1.6369196  -1.3771482  -0.59217227]
[-1.2167064 -0.9686053 -1.126445 ]
[-1.5345887 -1.0846399 -0.8064678]
[-2.3795917  -1.5385686  -0.36712444]
[-0.8273308 -1.0374719 -1.5681236]
[-2.5155637 -1.8459495 -0.2727182]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.0609115 -1.0536181 -1.1868341]
[-1.2269471 -0.970805  -1.1146326]
[-1.2818993 -1.0065879 -1.0299454]
[-2.662344   -1.7603421  -0.27676904]
[-1.3595679  -1.0529394  -0.93059856]
[-1.3595679  -1.0529394  -0.93059856]
[-1.5319409 -1.0601026 -0.826761 ]
[-1.3595679  -1.0529394  -0.93059856]
[-0.8790023 -1.0767784 -1.4101293]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0749186 -0.9513954 -1.300217 ]
[-1.4893112 -1.0806868 -0.8321571]
[-1.3421812 -0.9942912 -0.9976655]
[-1.1034701 -0.9539781 -1.2620385]
[-1.1251956 -1.098259  -1.073062 ]
[-2.189497   -1.9687753  -0.28981888]
[-1.2167072 -0.9686014 -1.1264489]
[-1.2121415 -0.8904211 -1.23114

[-1.2818762 -1.0064833 -1.0300704]
[-1.1032983 -0.9536011 -1.262753 ]
[-1.9264256 -1.6213034 -0.4205415]
[-1.6369196  -1.3771482  -0.59217227]
[-1.1546028 -0.9833072 -1.1687815]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0977687 -1.0755092 -1.1231264]
[-2.3795917  -1.5385686  -0.36712444]
[-2.1442528  -1.7235308  -0.35039547]
[-0.9505131 -1.0615206 -1.318531 ]
[-2.3795917  -1.5385686  -0.36712444]
[-2.3795917  -1.5385686  -0.36712444]
[-1.0149544 -0.9310688 -1.4128486]
[-1.0149544 -0.9310688 -1.4128486]
[-0.91981006 -0.93436277 -1.5674847 ]
[-1.0149544 -0.9310688 -1.4128486]
[-1.1191106 -0.9368456 -1.2673817]
[-1.0823123 -0.9571674 -1.2829806]
[-0.91982394 -0.93437284 -1.5674388 ]
[-0.91982394 -0.93437284 -1.5674388 ]
[-0.90637946 -1.0880345  -1.3503957 ]
[-1.248852  -0.9945598 -1.0692091]
[-1.2488637 -0.9945763 -1.0691817]
[-1.2167071  -0.96860075 -1.1264496 ]
[-1.3400743  -0.993491   -0.99996597]
[-1.0671576 -1.0736902 -1.157503 ]
[-1.057228  -1.0600885 -1.183656 ]
[-1.0671576 -1.0736902

[-1.2224703  -0.98311985 -1.1045611 ]
[-1.1068693 -1.1162485 -1.0732325]
[-1.0167276 -1.0885546 -1.198918 ]
[-1.4285569  -1.0290843  -0.90879047]
[-1.2111783 -1.1029553 -0.993536 ]
[-1.157887  -0.9841513 -1.1644495]
[-1.0401438 -1.0342847 -1.2340348]
[-1.0474266  -0.91547275 -1.3909724 ]
[-1.0391347 -1.0954082 -1.165277 ]
[-0.8434961 -1.0669858 -1.4883176]
[-1.288087  -1.0258365 -1.0059266]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.0610398 -1.0703304 -1.1679332]
[-1.0387322 -1.0340638 -1.2360215]
[-1.5467741  -0.9409997  -0.92425054]
[-1.3399963  -0.99348587 -1.0000265 ]
[-1.0676973 -1.068621  -1.1624504]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3795917  -1.5385686  -0.36712444]
[-2.1442528  -1.7235308  -0.35039547]
[-1.1553819  -0.98352957 -1.1677244 ]
[-1.2540557 -0.9974698 -1.0617692]
[-1.3450462  -0.9944557  -0.99547577]
[-1.1068693 -1.1162485 -1.0732325]
[-0.96746874 -1.067135   -1.2874866 ]
[-0.9290692 -1.0617886 -1.3499928]
[-0.8304722 -1.0668232 -1.5138705]
[-1.0451324 -1.1004547 -1

[-1.3402292  -0.99363494 -0.9997108 ]
[-1.6556755 -1.1699848 -0.6958201]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2167355 -0.9686601 -1.1263539]
[-1.2167175 -0.9686179 -1.12642  ]
[-1.0810419 -1.1559025 -1.0613606]
[-1.6369196  -1.3771482  -0.59217227]
[-1.9264256 -1.6213034 -0.4205415]
[-1.0744797 -1.092756  -1.1293802]
[-1.9264256 -1.6213034 -0.4205415]
[-2.189497   -1.9687753  -0.28981888]
[-2.189497   -1.9687753  -0.28981888]
[-1.1425806 -1.1245252 -1.0322669]
[-1.0929248 -1.0843226 -1.118913 ]
[-1.9264256 -1.6213034 -0.4205415]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0929248 -1.0843226 -1.118913 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.6369196  -1.3771482  -0.59217227]
[-2.1442528  -1.7235308  -0.35039547]
[-1.0609115 -1.0536181 -1.1868341]
[-1.9264256 -1.6213034 -0.4205415]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2228856 -1.049057  -1.0346446]
[-1.1834517 -1.1648097 -0.9628636]
[-1.3400764 -0.9934912 -0.9999641]
[-1.0838778 -1.076588  -1.1364309]

[-1.6369196  -1.3771482  -0.59217227]
[-1.2687905 -1.0052599 -1.0416301]
[-1.0929248 -1.0843226 -1.118913 ]
[-1.8630877 -1.2943213 -0.5608505]
[-2.662344   -1.7603421  -0.27676904]
[-2.662344   -1.7603421  -0.27676904]
[-1.216726   -0.96861434 -1.1264166 ]
[-1.2167194 -0.9686032 -1.1264353]
[-2.1442528  -1.7235308  -0.35039547]
[-1.2490774 -0.9974637 -1.0659018]
[-1.8123052 -1.1733416 -0.6398128]
[-1.7778885  -1.3079631  -0.57868487]
[-1.6369196  -1.3771482  -0.59217227]
[-2.3795917  -1.5385686  -0.36712444]
[-1.288087  -1.0258365 -1.0059266]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3660455 -1.7839618 -0.303571 ]
[-0.8292158 -1.0400267 -1.5598702]
[-1.9264256 -1.6213034 -0.4205415]
[-1.6369196  -1.3771482  -0.59217227]
[-2.5155637 -1.8459495 -0.2727182]
[-1.2576051  -1.0774612  -0.98027724]
[-2.1442528  -1.7235308  -0.35039547]
[-1.3423071 -0.9972478 -0.9946188]
[-2.5155637 -1.8459495 -0.2727182]
[-1.8630877 -1.2943213 -0.5608505]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0759687  -0.996519

[-1.2167636 -0.9687141 -1.126265 ]
[-1.2228853 -1.0489886 -1.0347122]
[-1.2202207  -0.97299004 -1.1181508 ]
[-1.2561219 -0.9434244 -1.1210074]
[-1.2231627 -1.0491729 -1.034301 ]
[-2.292894   -1.4866812  -0.39615217]
[-1.0754204 -1.0746931 -1.1474564]
[-2.189497   -1.9687753  -0.28981888]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.0754204 -1.0746931 -1.1474564]
[-1.0400969 -1.0343142 -1.234056 ]
[-0.991351  -1.0874683 -1.2314942]
[-2.189497   -1.9687753  -0.28981888]
[-1.2504578 -1.0138847 -1.0474837]
[-1.0836029 -1.0801271 -1.1329755]
[-1.2169158 -0.9690255 -1.1257619]
[-1.3413875  -1.0064013  -0.98621625]
[-1.3428216 -0.9950709 -0.9964306]
[-1.2511623 -1.0144613 -1.046313 ]
[-1.9547207  -1.1988139  -0.58546954]
[-1.4646614  -0.93111485 -0.9815505 ]
[-1.0754204 -1.0746931 -1.1474564]
[-1.2167697  -0.96867204 -1.1263086 ]
[-0.903859  -1.0880483 -1.3543192]
[-1.2953172 -1.0066085 -1.0196182]
[-1.3405788  -0.9935804  -0.99951714]
[-1.3423939 -1.0133655 -0.9787378]
[-1.257923  -1.0777881 -0.97

[-1.2488439 -0.9945634 -1.069212 ]
[-1.7478129 -1.3159838 -0.5840502]
[-1.2488772 -0.9946232 -1.06912  ]
[-1.262977  -1.0015095 -1.0502092]
[-1.2488458 -0.9945607 -1.0692133]
[-1.0592486 -1.0790089 -1.16043  ]
[-1.1807563  -1.2076094  -0.93129617]
[-1.8986673 -1.3295817 -0.5350431]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.0732856 -1.2058585 -1.0253196]
[-0.94696313 -1.0323555  -1.3629069 ]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0669965 -1.0835371 -1.1470783]
[-1.0729352 -1.0735646 -1.1513528]
[-1.0586679 -1.0630634 -1.1786748]
[-1.0584675 -1.0565369 -1.1862798]
[-1.8630877 -1.2943213 -0.5608505]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0577184 -1.0600567 -1.183136 ]
[-1.0676965 -1.1414357 -1.0881463]
[-1.3406556 -0.9936053 -0.9994374]
[-1.3436238  -0.9954215  -0.99551296]
[-2.0888612  -1.4295545  -0.45136815]
[-1.0582222 -1.0644946 -1.1775725]
[-1.0388967 -1.0340682 -1.2358156]
[-1.0387228 -1.0340273 -1.2360777]
[-1.4651308  -0.93399256 -0.978244  ]
[-1.0583057 -1.0601068 -1.182414 ]
[-1.0

[-1.3400763  -0.9934912  -0.99996424]
[-1.2488532  -0.99456954 -1.0691975 ]
[-1.0766456  -1.240622   -0.99409246]
[-1.216706   -0.96860653 -1.1264439 ]
[-1.0734687 -1.074008  -1.1502969]
[-1.3821198 -0.9578891 -1.0071672]
[-1.0731654 -1.20609   -1.0252409]
[-1.2576058 -1.0774763 -0.9802631]
[-1.2708298 -1.0208124 -1.0241567]
[-1.2708298 -1.0208124 -1.0241567]
[-1.2489207 -0.9945632 -1.0691482]
[-1.3436514 -0.9980726 -0.9928491]
[-1.0731654 -1.20609   -1.0252409]
[-1.1931499  -1.2969732  -0.85949093]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-0.92620975 -1.0527515  -1.3666027 ]
[-1.4464653  -1.2678977  -0.72737324]
[-1.0609812 -1.0703287 -1.1680002]
[-1.2322078 -1.4197991 -0.7623057]
[-1.4666686 -0.9325331 -0.9788267]
[-0.9950488 -1.1388571 -1.1708283]
[-1.2269366 -0.9707982 -1.1146502]
[-1.1718614 -1.2696589 -0.8933487]
[-1.0302962 -1.1142663 -1.1553642]
[-1.3427467  -0.99501014 -0.9965445 ]
[-1.654784  -1.1692014 -0.6966496]
[-0.8899626 -1.1125569 -1.34472

[-2.3660455 -1.7839618 -0.303571 ]
[-1.3428216 -0.9950709 -0.9964306]
[-2.1442528  -1.7235308  -0.35039547]
[-1.2181113 -0.9689006 -1.1248176]
[-1.2269366 -0.9707982 -1.1146502]
[-1.8630877 -1.2943213 -0.5608505]
[-1.6369196  -1.3771482  -0.59217227]
[-1.6369196  -1.3771482  -0.59217227]
[-1.3428216 -0.9950709 -0.9964306]
[-2.189497   -1.9687753  -0.28981888]
[-1.3410084  -0.99382734 -0.99896336]
[-1.6369196  -1.3771482  -0.59217227]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2269366 -0.9707982 -1.1146502]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.6369196  -1.3771482  -0.59217227]
[-1.2167077 -0.9686031 -1.126446 ]
[-2.662344   -1.7603421  -0.27676904]
[-1.6369196  -1.3771482  -0.59217227]
[-1.2541273 -1.0159228 -1.0424008]
[-1.2825668 -1.0068703 -1.0291382]
[-1.2492015 -0.9949464 -1.068501 ]
[-2.3795917  -1.5385686  -0.36712444]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2490442 -0.9946181 -1.0689857]
[-1.8630877 -1.2943213 -0.5608505]
[-1.8630877 -1.2943213 -0.5608505]
[-1.350821  -1.002033 

[-1.1478788  -0.94560766 -1.2233342 ]
[-0.92006475 -0.93442696 -1.5668771 ]
[-1.1191381  -0.93685365 -1.2673384 ]
[-1.3422043  -0.9943075  -0.99763274]
[-0.9198254 -0.9343613 -1.5674582]
[-1.2450479  -1.1704286  -0.91170394]
[-1.2167318 -0.9689935 -1.1259673]
[-1.3514527  -0.9972131  -0.98824334]
[-1.2569025  -1.0742794  -0.98370755]
[-1.3332405  -1.0728676  -0.93051106]
[-1.0977386 -1.0755023 -1.1231644]
[-1.4091005 -1.1863313 -0.7978466]
[-1.248843  -0.9945609 -1.0692158]
[-1.0929248 -1.0843226 -1.118913 ]
[-1.6545471  -1.1889397  -0.68462884]
[-1.530992  -1.0622864 -0.8255033]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2181113 -0.9689006 -1.1248176]
[-1.2553786 -0.9998547 -1.0581447]
[-1.530992  -1.0622864 -0.8255033]
[-1.2744589 -1.0110208 -1.0312238]
[-1.8193091 -1.2939634 -0.5732679]
[-1.3428216 -0.9950709 -0.9964306]
[-1.28025   -1.0306071 -1.0071957]
[-1.5319409 -1.0601026 -0.826761 ]
[-1.7478129 -1.3159838 -0.5840502]
[-2.1818597  -1.5169873  -0.40377155]
[-1.0731386 -1.0764055 -1

[-1.2167338 -0.9686074 -1.126417 ]
[-1.2508459 -0.9954567 -1.0665824]
[-2.3795917  -1.5385686  -0.36712444]
[-1.3410084  -0.99382734 -0.99896336]
[-1.3415849 -0.9973037 -0.9950733]
[-1.038754  -1.0340794 -1.2359756]
[-2.3795917  -1.5385686  -0.36712444]
[-1.7475793  -1.4800913  -0.51385015]
[-1.3401413  -0.99356425 -0.9998443 ]
[-2.662344   -1.7603421  -0.27676904]
[-1.2629629 -1.0015295 -1.0501993]
[-1.3427467  -0.99501014 -0.9965445 ]
[-2.0098548  -1.3618937  -0.49459693]
[-1.0730951 -1.0736431 -1.1510948]
[-1.4285569  -1.0290843  -0.90879047]
[-1.8630877 -1.2943213 -0.5608505]
[-2.1442528  -1.7235308  -0.35039547]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0382769 -0.9093361 -1.4141008]
[-1.0609957 -1.0703305 -1.1679822]
[-1.8469458 -1.2458358 -0.5895415]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2181113 -0.9689006 -1.1248176]
[-1.654784  -1.1692014 -0.6966496]
[-2.1442528  -1.7235308  -0.35039547]
[-1.248847  -0.9945631 -1.0692099]
[-1.2687905 -1.0052599 -1.0416301]
[-1.8630877 -1.2943

[-2.3795917  -1.5385686  -0.36712444]
[-2.189497   -1.9687753  -0.28981888]
[-2.01531    -1.6818885  -0.38463572]
[-1.7478129 -1.3159838 -0.5840502]
[-2.017219  -1.6879745 -0.3826062]
[-1.3522568  -0.9973865  -0.98751277]
[-1.9044303 -1.155525  -0.6232474]
[-0.98421216 -1.0750476  -1.2553189 ]
[-1.0578938 -1.0600703 -1.1829218]
[-1.6604592  -1.0686889  -0.76251936]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.4650049 -0.9313955 -0.9810435]
[-1.332084  -1.0385599 -0.9620487]
[-2.662344   -1.7603421  -0.27676904]
[-1.4441442 -1.1145935 -0.830105 ]
[-1.602726  -1.2000234 -0.6982282]
[-1.2473686 -0.976562  -1.0902377]
[-1.2137781 -1.0945162 -0.9990591]
[-1.2251182 -0.9754093 -1.1109715]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2508459  -0.99545753 -1.0665814 ]
[-2.189497   -1.9687753  -0.28981888]
[-1.2167168  -0.96861106 -1.1264286 ]
[-1.2508459  -0.99545753 -1.0665814 ]
[-2.662344   -1.7603421  -0.27676904]
[-1.3410015 -0.9938218 -0.9989738]
[-1.7809217 -1.4314

[-1.2169225 -0.9686657 -1.1261766]
[-1.3479583 -0.9961533 -0.9917348]
[-1.8630877 -1.2943213 -0.5608505]
[-2.5155637 -1.8459495 -0.2727182]
[-1.7478129 -1.3159838 -0.5840502]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2339828 -1.1316135 -0.9509941]
[-1.0929248 -1.0843226 -1.118913 ]
[-1.3479583 -0.9961533 -0.9917348]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.2489184 -0.9945624 -1.0691508]
[-1.2508459 -0.9954567 -1.0665824]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.3402244 -0.993647  -0.9997021]
[-1.7478129 -1.3159838 -0.5840502]
[-2.5155637 -1.8459495 -0.2727182]
[-1.2167096 -0.9686041 -1.1264433]
[-1.6027699  -1.200062   -0.69818705]
[-1.5455526  -0.99697995 -0.8727193 ]
[-1.8716068 -1.3797073 -0.5200823]
[-1.7478129 -1.3159838 -0.5840502]
[-1.2488472 -0.9946138 -1.069155 ]
[-1.2631968  -0.99240613 -1.0596775 ]
[-2.3795917  -1.5385686  -0.36712444]
[-0.8793624 -1.0768206 -1.4094582]
[-1.3479928 -0.9960439 -0.9918196]
[-1.7478129 -1.3159838 -0.5840502]
[-1.058062  -1.0600743 -1.1827265]
[-1.2533

[-1.2373807  -0.99036956 -1.0834752 ]
[-1.6123599  -1.3264189  -0.62519425]
[-2.5155637 -1.8459495 -0.2727182]
[-0.83250755 -1.0694277  -1.5058084 ]
[-2.2217617  -1.4917824  -0.40554896]
[-1.8630877 -1.2943213 -0.5608505]
[-0.8304854 -1.0668211 -1.5138478]
[-2.2217617  -1.4917824  -0.40554896]
[-1.7478129 -1.3159838 -0.5840502]
[-1.1265023  -1.2659488  -0.93175155]
[-1.267941  -1.1445265 -0.9157535]
[-1.3428216 -0.9950709 -0.9964306]
[-1.0769755 -1.0768118 -1.1435182]
[-1.2571312 -1.020635  -1.0351729]
[-1.3701496  -1.1683366  -0.83230025]
[-0.9560239 -1.0644403 -1.306889 ]
[-1.1417972 -1.1041356 -1.0519446]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.2705698 -1.0926783 -0.9570835]
[-1.3362997 -1.0346487 -0.9627736]
[-1.2493167 -0.9950012 -1.0683458]
[-0.9261508 -1.055324  -1.3631834]
[-1.0391161 -1.0345155 -1.2350018]
[-1.2493167 -0.9950012 -1.0683458]
[-1.3404844  -0.99409014 -0.99907166]
[-1.119328  -0.9771072 -1.2136779]
[-1.4414608  -1.2449043  -0.74349433]
[-1.2488472 -0.9946135 -1.06

[-1.4123158 -1.2085471 -0.7813434]
[-1.4648514  -0.9312177  -0.98132515]
[-1.248919  -0.9945616 -1.0691512]
[-1.7478129 -1.3159838 -0.5840502]
[-1.2168254 -0.9686974 -1.1262282]
[-1.2897506 -1.1547577 -0.8927533]
[-1.7478129 -1.3159838 -0.5840502]
[-1.3402286 -0.9936507 -0.9996954]
[-1.2488445  -0.99456763 -1.069207  ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.0593904 -1.0791022 -1.1601715]
[-1.1023077 -1.0443354 -1.1521063]
[-1.8630877 -1.2943213 -0.5608505]
[-1.05773  -1.060145 -1.183023]
[-1.0508608 -1.0386434 -1.2159483]
[-2.3660455 -1.7839618 -0.303571 ]
[-0.89800787 -1.0647483  -1.3951132 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.3595679  -1.0529394  -0.93059856]
[-1.7478129 -1.3159838 -0.5840502]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.3736591 -1.0047017 -0.9658295]
[-1.3905909 -1.0376248 -0.9243818]
[-1.654784  -1.1692014 -0.6966496]
[-0.9252958 -1.050068  -1.3717134]
[-1.0360769 -1.0934446 -1.1708748]
[-1.040064  -1.0342698 -1.23415  ]
[-1.2

[-1.1312487 -0.9399174 -1.249285 ]
[-1.0728735 -1.0735276 -1.1514593]
[-1.4474769 -1.3039073 -0.7064998]
[-1.2465872 -1.0002891 -1.0649571]
[-0.8898116 -1.0900068 -1.3741577]
[-1.2907503 -1.0370619 -0.9930611]
[-1.2169029  -0.96865594 -1.1262059 ]
[-1.474514  -1.2914531 -0.7006976]
[-1.2181113 -0.9689006 -1.1248176]
[-1.3400106 -0.9934966 -1.0000055]
[-0.9048226 -1.0882577 -1.3525363]
[-2.3660455 -1.7839618 -0.303571 ]
[-0.8899626 -1.1125569 -1.3447244]
[-1.040737   -0.92734206 -1.3814983 ]
[-1.6369196  -1.3771482  -0.59217227]
[-0.9066567 -1.0878558 -1.3501956]
[-1.3399912 -0.9934864 -1.0000298]
[-1.3595679  -1.0529394  -0.93059856]
[-1.2277219 -1.0530441 -1.0267568]
[-1.6868798 -1.2803277 -0.6218362]
[-0.88323   -1.0627638 -1.4227298]
[-2.1442528  -1.7235308  -0.35039547]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.3867068 -1.1649377 -0.8251688]
[-1.7172179  -1.160936   -0.67876697]
[-1.3410084  -0.99382734 -0.99896336]

[-1.7663517 -1.3235986 -0.5747089]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.4278497  -1.0284823  -0.90974545]
[-1.2508459 -0.9954567 -1.0665824]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2508459 -0.9954567 -1.0665824]
[-1.2181401 -0.9689748 -1.1247046]
[-1.2897506 -1.1547577 -0.8927533]
[-2.5155637 -1.8459495 -0.2727182]
[-1.2508459 -0.9954567 -1.0665824]
[-2.3795917  -1.5385686  -0.36712444]
[-1.7809217 -1.4314935 -0.523294 ]
[-2.5155637 -1.8459495 -0.2727182]
[-2.189497   -1.9687753  -0.28981888]
[-1.2508459 -0.9954567 -1.0665824]
[-1.262977  -1.0015095 -1.0502092]
[-2.1442528  -1.7235308  -0.35039547]
[-1.9595022  -1.6580477  -0.40262792]
[-1.7478129 -1.3159838 -0.5840502]
[-1.2528801 -0.9795134 -1.0822701]
[-1.4278497  -1.0284823  -0.90974545]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2506809 -0.9956736 -1.0664868]
[-1.2428002 -0.9935667 -1.0753708]
[-2.1442528  -1.7235308  -0.35039547]
[-2.3795917  -1.5385686  -0.36712444]
[-1.530992  -1.0622864 -0.82

[-1.6556755 -1.1699848 -0.6958201]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.4278497  -1.0284823  -0.90974545]
[-2.3795917  -1.5385686  -0.36712444]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2913027  -1.0425408  -0.98743826]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.7478129 -1.3159838 -0.5840502]
[-1.2629768 -1.0015087 -1.0502099]
[-1.6556755 -1.1699848 -0.6958201]
[-1.4278497  -1.0284823  -0.90974545]
[-1.7478129 -1.3159838 -0.5840502]
[-1.3427467  -0.99501014 -0.9965445 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.248843  -0.9945605 -1.069216 ]
[-1.262977  -1.0015095 -1.0502092]
[-1.3227901 -1.1649879 -0.8635024]
[-2.1442528  -1.7235308  -0.35039547]
[-1.8630877 -1.2943213 -0.5608505]
[-1.7478129 -1.3159838 -0.5840502]
[-0.92955136 -1.0520355  -1.3624097 ]
[-1.3400421  -0.99389476 -0.9995826 ]
[-2.1442528  -1.7235308  -0.35039547]
[-1.4278497  -1.0284823  -0.90974545]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0387421 -1.0340443 -1.2360333]
[-1.0730523 -1.0736398

[-1.2535717  -0.99963397 -1.059865  ]
[-1.2492974  -0.99508566 -1.0682709 ]
[-1.0400217 -1.0342376 -1.2342407]
[-1.5433593 -0.9376246 -0.9294239]
[-1.7778885  -1.3079631  -0.57868487]
[-2.1442528  -1.7235308  -0.35039547]
[-1.0723466 -1.0733148 -1.1522597]
[-1.0725497 -1.0734007 -1.1519465]
[-1.2510834  -0.99567664 -1.0661488 ]
[-2.189497   -1.9687753  -0.28981888]
[-1.3405614  -0.99352485 -0.9995852 ]
[-1.2832011 -1.02726   -1.0082282]
[-1.3410084  -0.99382734 -0.99896336]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.5146887  -1.0055883  -0.88117945]
[-1.2488594 -0.994575  -1.0691867]
[-1.0582404 -1.0601896 -1.1823941]
[-1.058121  -1.0600812 -1.182652 ]
[-2.662344   -1.7603421  -0.27676904]
[-1.0193067 -1.093675  -1.1901627]
[-1.3399994 -0.9934789 -1.0000314]
[-1.3400018  -0.99354154 -0.99996656]
[-1.2762734 -1.0044447 -1.0365486]
[-1.0729095 -1.0735078 -1.151442 ]
[-2.662344   -1.7603421  -0.27676904]
[-1.216707  -0.968601  -1.1264492]
[-1.340017  -0.9935044 -0.9999932]
[-1.248919  -0.9945

[-0.9440579 -1.1980815 -1.1738267]
[-1.2181115  -0.96889967 -1.1248186 ]
[-1.2181113 -0.9689006 -1.1248176]
[-1.2167076  -0.96860075 -1.1264489 ]
[-1.2521403 -0.9868819 -1.0747864]
[-1.1149681 -0.9530043 -1.2500398]
[-1.236042  -0.9916746 -1.0831923]
[-1.251848   -0.98687196 -1.075042  ]
[-1.5763829  -1.1380498  -0.74900824]
[-1.2181115  -0.96889967 -1.1248186 ]
[-1.3537494 -1.0822653 -0.90906  ]
[-1.0314246 -0.9213835 -1.4043231]
[-0.8744153 -1.089042  -1.4009798]
[-1.0849065 -1.0717301 -1.1405252]
[-1.2538965 -1.0064132 -1.0524493]
[-1.22594    -0.97576255 -1.1098344 ]
[-1.3155484 -1.0622373 -0.9519404]
[-1.2508459 -0.9954567 -1.0665824]
[-1.7148046 -1.251606  -0.6274417]
[-1.3515396  -0.99962944 -0.9857941 ]
[-1.0929248 -1.0843226 -1.118913 ]
[-1.3467883 -1.0180941 -0.9711616]
[-1.248843  -0.9945601 -1.0692164]
[-1.22313    -0.96867985 -1.1205246 ]
[-0.926181  -1.0526853 -1.3667378]
[-0.95483625 -1.0624764  -1.3110907 ]
[-1.7663517 -1.3235986 -0.5747089]
[-1.1068693 -1.1162485 -1.07

[-1.0582379 -1.0629138 -1.1793276]
[-1.0685211 -1.0829306 -1.1460748]
[-1.0799377 -1.224581  -1.0037498]
[-1.0591681 -1.0789342 -1.1605996]
[-1.2975371 -1.0098232 -1.0146958]
[-1.0588504 -1.0629858 -1.178556 ]
[-1.1444571  -1.224445   -0.94756866]
[-1.0464844 -1.0929422 -1.1596335]
[-1.4069471 -1.1247647 -0.8430837]
[-1.0650625 -1.14146   -1.0908189]
[-1.0149626  -0.93107283 -1.41283   ]
[-1.3591343 -1.0019739 -0.9782646]
[-0.8198209 -1.0379928 -1.5831629]
[-1.2625601 -0.99929   -1.0528826]
[-1.1412163 -1.1234761 -1.034449 ]
[-1.3405597  -0.996559   -0.99654317]
[-0.8198863 -1.0380013 -1.5830078]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0643702 -1.1409166 -1.0920472]
[-2.1442528  -1.7235308  -0.35039547]
[-1.2492974  -0.99508566 -1.0682709 ]
[-0.87898594 -1.0767694  -1.4101701 ]
[-1.0365995 -1.0778828 -1.1873584]
[-1.2167091 -0.9686542 -1.126385 ]
[-1.24887   -0.9945812 -1.0691711]
[-1.2488422  -0.99455976 -1.0692173 ]
[-1.8630877 -1.2943213 -0.5608505]
[-1.8630877 -1.2943213 -0.5608505]

[-1.2952697 -1.0062797 -1.0199871]
[-1.4807318 -1.223022  -0.737748 ]
[-1.3436935  -0.99772596 -0.99316466]
[-1.8630877 -1.2943213 -0.5608505]
[-1.5318878 -1.0600581 -0.8268226]
[-0.9268749 -1.0618002 -1.3533292]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0998256 -1.2524025 -0.9642907]
[-1.2167339  -0.96860987 -1.1264143 ]
[-0.9232292 -1.0618289 -1.358901 ]
[-1.1358784 -1.1625762 -1.0046289]
[-1.3093034  -1.0451958  -0.97188544]
[-1.0787575 -1.2422864 -0.9908553]
[-1.3493748  -0.94933265 -1.0395937 ]
[-1.2950151 -1.0062367 -1.0202243]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.8956025  -1.28195    -0.55813295]
[-1.377323   -0.95240533 -1.0162902 ]
[-0.81987876 -1.0380509  -1.5829389 ]
[-1.5318878 -1.0600581 -0.8268226]
[-2.662344   -1.7603421  -0.27676904]
[-1.2489002 -0.994628  -1.0690954]
[-2.1442528  -1.7235308  -0.35039547]
[-1.0796893 -1.0790061 -1.1382918]
[-1.5218221 -1.2446045 -0.7059661]
[-1.6369196  -1.3771482  -0.59217227]
[-1.8630877 -1.2943213 -0.5608505]
[-1.555541  -1.1591067 -0

[-1.2489085 -0.9949678 -1.0687226]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2618399 -0.9990479 -1.0537226]
[-2.3795917  -1.5385686  -0.36712444]
[-1.3687596 -1.0421457 -0.9342496]
[-1.7478129 -1.3159838 -0.5840502]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2508459 -0.9954567 -1.0665824]
[-1.2488884 -0.9946364 -1.0690962]
[-2.189497   -1.9687753  -0.28981888]
[-1.5912435  -1.1143982  -0.75882715]
[-2.189497   -1.9687753  -0.28981888]
[-1.3405721  -0.9935338  -0.99956864]
[-1.3674101 -1.0256206 -0.9502089]
[-1.5328633 -1.0614476 -0.8252424]
[-1.2508589 -0.9957715 -1.0662335]
[-1.0481094 -1.0353827 -1.2231232]
[-2.189497   -1.9687753  -0.28981888]
[-1.0405499 -1.0344787 -1.2333056]
[-1.2859108  -1.4509802  -0.71485966]
[-1.3362997 -1.0346487 -0.9627736]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.854986   -1.3864634  -0.52157134]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.074834  -0.9512758 -1.3004924]
[-1.340352   -0.99378395 -0.9994736 ]
[-1.6954685 -1.2635665 -0.6276542]
[-1.071774  -1.0790992 -1

[-1.2581761  -1.1620207  -0.90888137]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.8630877 -1.2943213 -0.5608505]
[-1.8630877 -1.2943213 -0.5608505]
[-1.4278497  -1.0284823  -0.90974545]
[-1.8630877 -1.2943213 -0.5608505]
[-1.255101  -1.0026877 -1.0553778]
[-1.0652043 -1.1418855 -1.0902692]
[-2.3660455 -1.7839618 -0.303571 ]
[-0.8304492 -1.066827  -1.5139099]
[-1.0977718 -1.0755149 -1.1231172]
[-0.9262092 -1.0530828 -1.36615  ]
[-0.9260976 -1.0702591 -1.3432968]
[-1.9595022  -1.6580477  -0.40262792]
[-1.0728738 -1.0734937 -1.1514958]
[-1.0729102 -1.0735145 -1.1514335]
[-1.2508459 -0.9954567 -1.0665824]
[-1.7478129 -1.3159838 -0.5840502]
[-2.5155637 -1.8459495 -0.2727182]
[-1.2489192 -0.9945634 -1.0691493]
[-1.216712  -0.9686552 -1.1263813]
[-2.662344   -1.7603421  -0.27676904]
[-1.2488434 -0.9945682 -1.0692073]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.662344   -1.7603421  -0.27676904]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2678087 -1.0066541 -1.0409681]
[-2.3795917  -1.5385686  -0.36712444]

[-1.2554195 -0.9965138 -1.0616648]
[-1.2229081 -1.0490811 -1.0346024]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3795917  -1.5385686  -0.36712444]
[-1.227385   -0.99484473 -1.087194  ]
[-1.4188788  -1.1922951  -0.78857714]
[-1.2491016 -0.997472  -1.0658727]
[-1.342217  -1.0133133 -0.978911 ]
[-1.3400023  -0.99354184 -0.9999659 ]
[-1.0729383 -1.0735667 -1.151347 ]
[-1.392451   -0.97554815 -0.98203325]
[-1.2541937  -0.99955344 -1.0594386 ]
[-1.2167065 -0.9685936 -1.1264583]
[-1.8956025  -1.28195    -0.55813295]
[-1.4278497  -1.0284823  -0.90974545]
[-1.3796527  -1.0666316  -0.90592414]
[-1.288087  -1.0258365 -1.0059266]
[-1.0481633 -1.0353605 -1.2230858]
[-1.3410084  -0.99382734 -0.99896336]
[-1.2181444 -0.968919  -1.1247659]
[-1.8193091 -1.2939634 -0.5732679]
[-2.3795917  -1.5385686  -0.36712444]
[-1.0669664 -1.0760201 -1.1551839]
[-1.2644546  -0.99066955 -1.0605111 ]
[-1.2935684  -0.95216197 -1.0793865 ]
[-1.2553786 -0.9998547 -1.0581447]
[-1.1553628  -0.98352206 -1.1677526 ]
[-1.629535  -

[-0.9198243 -0.9343625 -1.5674582]
[-1.0213871 -0.9328626 -1.4004784]
[-0.91981333 -0.9343607  -1.567483  ]
[-0.9198246 -0.934371  -1.5674413]
[-1.0396919 -0.9288487 -1.3805978]
[-1.2828715 -0.9767121 -1.0607015]
[-0.9198098  -0.93436277 -1.5674851 ]
[-0.91066766 -1.0711195  -1.3660225 ]
[-1.0149186 -0.9310689 -1.4129018]
[-0.91788304 -0.9500027  -1.5422634 ]
[-0.91981065 -0.9343636  -1.5674818 ]
[-0.9198115 -0.9343684 -1.5674713]
[-0.9200134  -0.93437684 -1.5670695 ]
[-2.189497   -1.9687753  -0.28981888]
[-2.1442528  -1.7235308  -0.35039547]
[-1.0147235  -0.93353397 -1.4092131 ]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.5319409 -1.0601026 -0.826761 ]
[-1.0400082 -1.0341904 -1.2343146]
[-1.4468186 -1.2677464 -0.7272894]
[-2.3795917  -1.5385686  -0.36712444]
[-1.329065  -1.1005199 -0.9098681]
[-1.5319409 -1.0601026 -0.826761 ]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2508459 -0.9954567 -1.0665824]
[-2.3795917  -1.5385686  -0.36712444]
[-1.8630877 -1.2943213 -0.5608505]
[-1.0253015 -1.0899541

[-1.2168505  -0.97141886 -1.1230289 ]
[-1.0583352 -1.062943  -1.1791852]
[-2.3795917  -1.5385686  -0.36712444]
[-1.2171881 -0.9691892 -1.1253219]
[-1.2167282 -0.9686213 -1.1264062]
[-1.2869496 -1.0077263 -1.0248779]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2285855 -0.9793751 -1.1033798]
[-2.3795917  -1.5385686  -0.36712444]
[-1.6510983 -1.4168297 -0.5697278]
[-1.2489798 -0.9946337 -1.0690228]
[-2.5155637 -1.8459495 -0.2727182]
[-1.6027699  -1.200062   -0.69818705]
[-1.6027699  -1.200062   -0.69818705]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2181866 -0.9693572 -1.1242156]
[-1.1580415  -0.98692983 -1.1609771 ]
[-1.2167878  -0.96860856 -1.1263666 ]
[-1.2567314 -1.0006047 -1.056242 ]
[-1.2168052 -0.9686165 -1.1263412]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.3094013 -1.0140648 -1.0016395]
[-1.1550565 -0.9837851 -1.167747 ]
[-1.216804  -0.9686165 -1.1263424]
[-2.3795917  -1.5385686  -0.36712444]
[-1.447793  -1.3042297 -0.7061717]
[-1.225016   -0.97495615 -1.1115816 ]
[-2.3795917  -1.5385686  -0.

[-2.3660455 -1.7839618 -0.303571 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.7809217 -1.4314935 -0.523294 ]
[-2.3795917  -1.5385686  -0.36712444]
[-1.0401464 -1.0343028 -1.2340099]
[-1.0481198 -1.035303  -1.2232069]
[-1.2508459  -0.99545753 -1.0665814 ]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2897506 -1.1547577 -0.8927533]
[-1.1549003 -0.9837214 -1.1679817]
[-1.8630877 -1.2943213 -0.5608505]
[-1.5318878 -1.0600581 -0.8268226]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.8630877 -1.2943213 -0.5608505]
[-1.7478129 -1.3159838 -0.5840502]
[-1.6123599  -1.3264189  -0.62519425]
[-1.0580741 -1.0600808 -1.1827056]
[-2.3795917  -1.5385686  -0.36712444]
[-1.371272  -1.0233305 -0.9497957]
[-1.3428216 -0.9950709 -0.9964306]
[-1.1056452 -1.096616  -1.0936149]
[-1.2167338 -0.9686074 -1.126417 ]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3795917  -1.5385686  -0.36712444]
[-0.82812524 -1.0380725  -1.565441  ]
[-1.6369196  -1.3771482  -0.592172

[-2.3795917  -1.5385686  -0.36712444]
[-1.8630877 -1.2943213 -0.5608505]
[-1.5791718 -1.0146241 -0.8409153]
[-1.2488432 -0.9945607 -1.0692153]
[-1.7478129 -1.3159838 -0.5840502]
[-1.0729107 -1.0735087 -1.1514393]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2679191  -1.1445024  -0.91578823]
[-1.9093685 -1.2386196 -0.5761785]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.3211894  -1.016346   -0.99083304]
[-1.2492015 -0.9949464 -1.068501 ]
[-1.3410084  -0.99382734 -0.99896336]
[-1.654784  -1.1692014 -0.6966496]
[-1.9093685 -1.2386196 -0.5761785]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.3269106 -1.0986995 -0.9127965]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2181113 -0.9689006 -1.1248176]
[-1.3410084  -0.99382734 -0.99896336]
[-1.4278497  -1.0284823  -0.90974545]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.8630877 -1.2943213 -0.5608505]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.0929248 -1.0843226 -1.118913 ]
[-1.2508459 -0.9954567 -1.0665824]
[-2.3660455 -1.7839618 -0.303571 ]
[-0.8199236 -1.0380147 -1.582905 ]
[-

[-1.091925  -1.1843228 -1.0258912]
[-1.468147   -0.9356785  -0.97463906]
[-0.82812524 -1.0380725  -1.565441  ]
[-1.4594041 -1.1238656 -0.8150792]
[-1.0742472 -1.0745318 -1.1488926]
[-1.2565778 -1.0192069 -1.0370681]
[-2.662344   -1.7603421  -0.27676904]
[-1.1175125 -1.2507045 -0.950353 ]
[-1.2320596 -1.0596533 -1.0168493]
[-2.3660455 -1.7839618 -0.303571 ]
[-1.2438785 -1.0633993 -1.0038772]
[-1.3400077  -0.99349487 -1.0000093 ]
[-1.6556755 -1.1699848 -0.6958201]
[-1.0929248 -1.0843226 -1.118913 ]
[-1.0929248 -1.0843226 -1.118913 ]
[-1.4183145  -1.1894034  -0.79081416]
[-1.2167355 -0.9686601 -1.1263539]
[-1.2137781 -1.0945162 -0.9990591]
[-2.189497   -1.9687753  -0.28981888]
[-1.2137781 -1.0945162 -0.9990591]
[-1.8630877 -1.2943213 -0.5608505]
[-1.2628214 -1.0022124 -1.0495971]
[-1.654784  -1.1692014 -0.6966496]
[-1.5558105  -0.98497057 -0.8781967 ]
[-1.5005671 -1.0458293 -0.8542645]
[-1.2137781 -1.0945162 -0.9990591]
[-1.262977  -1.0015095 -1.0502092]
[-1.7475793  -1.4800913  -0.513850

[-1.045593   -0.98494846 -1.2907729 ]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3795917  -1.5385686  -0.36712444]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.7478129 -1.3159838 -0.5840502]
[-1.250905   -0.99852073 -1.0632539 ]
[-1.2181113 -0.9689006 -1.1248176]
[-1.3406054 -0.994128  -0.9989476]
[-1.2874527 -1.0264766 -1.0057777]
[-2.01531    -1.6818885  -0.38463572]
[-1.061007  -1.0703456 -1.1679529]
[-0.9499574 -1.0620921 -1.3185956]
[-0.9608426 -1.0859481 -1.2735087]
[-2.3795917  -1.5385686  -0.36712444]
[-1.257668  -1.0776856 -0.9800258]
[-2.1442528  -1.7235308  -0.35039547]
[-2.1442528  -1.7235308  -0.35039547]
[-2.662344   -1.7603421  -0.27676904]
[-2.862689   -2.1074557  -0.19682026]
[-2.662344   -1.7603421  -0.27676904]
[-1.2623627 -0.9447056 -1.1140671]
[-2.662344   -1.7603421  -0.27676904]
[-1.6369196  -1.3771482  -0.59217227]
[-1.6369196  -1.3771482  -0.59217227]
[-1.6369196  -1.3771482  -0.59217227]
[-1.2624539 -0.9995332 -1.0527122]
[-0.83018994 -1.0669084  -1.5142963 ]
[-2.189497

[-1.860491   -1.2352078  -0.59125966]
[-1.351573   -1.112181   -0.88594055]
[-1.6369196  -1.3771482  -0.59217227]
[-1.6369196  -1.3771482  -0.59217227]
[-1.3427467  -0.99501014 -0.9965445 ]
[-0.82812524 -1.0380725  -1.565441  ]
[-1.3868785 -1.1650572 -0.8249858]
[-1.4311757 -1.0446095 -0.8936903]
[-1.6369196  -1.3771482  -0.59217227]
[-0.8870154 -1.0625985 -1.4165058]
[-2.01531    -1.6818885  -0.38463572]
[-1.5319409 -1.0601026 -0.826761 ]
[-1.3427467  -0.99501014 -0.9965445 ]
[-1.8630877 -1.2943213 -0.5608505]
[-2.3795917  -1.5385686  -0.36712444]
[-2.3660455 -1.7839618 -0.303571 ]
[-2.1442528  -1.7235308  -0.35039547]
[-1.227369   -0.97129583 -1.1136898 ]
[-1.3926766  -1.0396873  -0.92123985]
[-1.0455415  -0.97227997 -1.3083007 ]
[-1.7809217 -1.4314935 -0.523294 ]
[-1.6369196  -1.3771482  -0.59217227]
[-2.01531    -1.6818885  -0.38463572]
[-1.1158557 -1.2709613 -0.9369952]
[-1.1255828 -1.1028838 -1.0682068]
[-2.1442528  -1.7235308  -0.35039547]
[-1.2491186  -0.99516016 -1.0683403 ]
[

In [89]:
y_hat_character = np.argmax(predictions_character, axis=1)

In [96]:
sum(y_hat_character == 2)/len(y_hat_character)

0.5469687300574346

In [118]:
sum(y_hat_character == 0)

2307

In [117]:
sum(y_assess == 0)

5171

In [94]:
print(classification_report(y_hat_character, y_assess, target_names=['close', 'split', 'far']))

              precision    recall  f1-score   support

       close       0.21      0.47      0.29      2307
       split       0.35      0.38      0.37      4792
         far       0.77      0.48      0.59      8571

   micro avg       0.45      0.45      0.45     15670
   macro avg       0.45      0.44      0.42     15670
weighted avg       0.56      0.45      0.48     15670



In [123]:
accuracy_score(y_hat_character, y_assess)

0.4469049138481174

So that's interesting, naively doing this seems to mean that we are worse than chance... I think I must be doing something incorrectly. This seems unreasonably bad. I wonder if using bpe tokens as features would help at all (or even word features)

In [102]:
caption_phi_endings = caption_featurizers.CaptionFeaturizer(tokenizer = caption_featurizers.EndingTokenizer)

# we use a color featurizer because the code was designed to always use both color and text features. These 
# features will just be ignored in the model code
color_phi = color_featurizers.ColorFeaturizer(color_featurizers.color_phi_fourier, "hsv", normalized=True)
feature_handler_endings = FeatureHandler(train_data, dev_data, caption_phi_endings, color_phi, target_fn=condition_predictor_target, randomized_colors=False)

In [103]:
X_train_endings = feature_handler_endings.train_features()
y_train_endings = feature_handler_endings.train_targets()

In [104]:
condition_predictor_endings = ConditionPredictor(BaselineConditionPredictor, optimizer=torch.optim.Adam, lr=0.004, num_epochs=5)
condition_predictor_endings.init_model(vocab_size=caption_phi_endings.caption_indexer.size, 
                                         embed_dim=100, speaker_hidden_dim=100)

In [106]:
condition_predictor_endings.fit(X_train_endings, y_train_endings)

---EPOCH 0---
0m 0s (0:0 0.00%) 0.0012
0m 3s (0:1000 7.90%) 1.0270
0m 8s (0:2000 15.79%) 1.0476
0m 13s (0:3000 23.69%) 1.0439
0m 20s (0:4000 31.58%) 1.0302
0m 26s (0:5000 39.48%) 1.0205
0m 33s (0:6000 47.37%) 0.9947
0m 39s (0:7000 55.27%) 0.9759
0m 46s (0:8000 63.17%) 1.0362
0m 52s (0:9000 71.06%) 0.9631
0m 59s (0:10000 78.96%) 0.9812
1m 5s (0:11000 86.85%) 1.0094
1m 12s (0:12000 94.75%) 0.9997
AFTER EPOCH 2999 - AVERAGE VALIDATION LOSS: 1.012975144247214
---EPOCH 1---
1m 19s (1:0 0.00%) 0.0013
1m 26s (1:1000 7.90%) 0.9891
1m 33s (1:2000 15.79%) 1.0179
1m 40s (1:3000 23.69%) 1.0267
1m 48s (1:4000 31.58%) 1.0030
1m 55s (1:5000 39.48%) 0.9903
2m 2s (1:6000 47.37%) 0.9831
2m 8s (1:7000 55.27%) 0.9763
2m 15s (1:8000 63.17%) 1.0393
2m 22s (1:9000 71.06%) 0.9746
2m 29s (1:10000 78.96%) 0.9808
2m 36s (1:11000 86.85%) 1.0075
2m 43s (1:12000 94.75%) 1.0030
AFTER EPOCH 2999 - AVERAGE VALIDATION LOSS: 1.0154820242524147
---EPOCH 2---
2m 49s (2:0 0.00%) 0.0011
2m 56s (2:1000 7.90%) 0.9831
3m 4s (2

In [107]:
X_assess_endings = feature_handler_endings.test_features()
y_assess_endings = feature_handler_endings.test_targets()

In [108]:
predictions_endings = condition_predictor_endings.predict(X_assess_endings)
y_hat_endings = np.argmax(predictions_endings, axis=1)

In [109]:
print(classification_report(y_hat_endings, y_assess_endings, target_names=['close', 'split', 'far']))

              precision    recall  f1-score   support

       close       0.39      0.55      0.46      3713
       split       0.39      0.42      0.40      4863
         far       0.74      0.55      0.63      7094

   micro avg       0.51      0.51      0.51     15670
   macro avg       0.51      0.50      0.50     15670
weighted avg       0.55      0.51      0.52     15670



In [122]:
accuracy_score(y_hat_endings, y_assess_endings)

0.5068283343969369

In [110]:
# now for the subword features:
caption_phi_subword = caption_featurizers.CaptionFeaturizer(tokenizer = caption_featurizers.SentencePieceTokenizer)

feature_handler_subword = FeatureHandler(train_data, dev_data, caption_phi_subword, color_phi, target_fn=condition_predictor_target, randomized_colors=False)


In [111]:
X_train_subword = feature_handler_subword.train_features()
y_train_subword = feature_handler_subword.train_targets()

In [113]:
condition_predictor_subword = ConditionPredictor(BaselineConditionPredictor, optimizer=torch.optim.Adam, lr=0.004, num_epochs=5)
condition_predictor_subword.init_model(vocab_size=caption_phi_subword.caption_indexer.size, 
                                         embed_dim=100, speaker_hidden_dim=100)

In [114]:
condition_predictor_subword.fit(X_train_subword, y_train_subword)

---EPOCH 0---
0m 0s (0:0 0.00%) 0.0011
0m 3s (0:1000 7.90%) 1.0670
0m 7s (0:2000 15.79%) 1.0381
0m 11s (0:3000 23.69%) 1.0534
0m 17s (0:4000 31.58%) 1.0503
0m 21s (0:5000 39.48%) 1.0532
0m 26s (0:6000 47.37%) 1.0210
0m 29s (0:7000 55.27%) 1.0037
0m 33s (0:8000 63.17%) 1.0616
0m 37s (0:9000 71.06%) 0.9924
0m 41s (0:10000 78.96%) 1.0199
0m 44s (0:11000 86.85%) 1.0379
0m 48s (0:12000 94.75%) 1.0080
AFTER EPOCH 2999 - AVERAGE VALIDATION LOSS: 1.0338063392241796
---EPOCH 1---
0m 53s (1:0 0.00%) 0.0014
0m 56s (1:1000 7.90%) 1.0313
1m 0s (1:2000 15.79%) 1.0315
1m 4s (1:3000 23.69%) 1.0488
1m 9s (1:4000 31.58%) 1.0295
1m 13s (1:5000 39.48%) 1.0290
1m 17s (1:6000 47.37%) 1.0106
1m 20s (1:7000 55.27%) 0.9888
1m 24s (1:8000 63.17%) 1.0438
1m 28s (1:9000 71.06%) 0.9848
1m 32s (1:10000 78.96%) 0.9985
1m 35s (1:11000 86.85%) 1.0216
1m 38s (1:12000 94.75%) 1.0217
AFTER EPOCH 2999 - AVERAGE VALIDATION LOSS: 1.0292375600536665
---EPOCH 2---
1m 43s (2:0 0.00%) 0.0009
1m 47s (2:1000 7.90%) 1.0133
1m 52s 

In [115]:
X_assess_subword = feature_handler_subword.test_features()
y_assess_subword = feature_handler_subword.test_targets()

In [116]:
predictions_subword = condition_predictor_subword.predict(X_assess_subword)
y_hat_subword = np.argmax(predictions_subword, axis=1)
print(classification_report(y_hat_subword, y_assess_subword, target_names=['close', 'split', 'far']))

              precision    recall  f1-score   support

       close       0.29      0.52      0.37      2852
       split       0.35      0.40      0.37      4541
         far       0.77      0.49      0.60      8277

   micro avg       0.47      0.47      0.47     15670
   macro avg       0.47      0.47      0.45     15670
weighted avg       0.56      0.47      0.49     15670



In [120]:
accuracy_score(y_hat_subword, y_assess_subword)

0.4696873005743459

In [130]:
# I want to compare this with the pragmatic, so I'm going to use endings

predictions_training_subword = condition_predictor_subword.predict(X_train_subword)
y_hat_training_subword = np.argmax(predictions_training_subword, axis=1)
print(classification_report(y_hat_training_subword, y_train_subword, target_names=['close', 'split', 'far']))

              precision    recall  f1-score   support

       close       0.28      0.53      0.36      2727
       split       0.31      0.40      0.35      4071
         far       0.79      0.47      0.59      8867

   micro avg       0.46      0.46      0.46     15665
   macro avg       0.46      0.47      0.43     15665
weighted avg       0.58      0.46      0.49     15665



In [131]:
y_hat_training_subword[:10]

array([0, 2, 1, 1, 2, 2, 2, 2, 1, 2])

In [132]:
import pickle

with open("../results/condition_prediction_baseline_training_subword.pkl", "wb") as file:
    pickle.dump(y_hat_training_subword, file)